cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: achim.struve@outlierventures.io
      logged_in: false
      name: OV Admin
      password: $2b$12$vFRGsaLPTPHA4vpLfdRwyel3NMCZd9TVnAXluv/Dbv0d1DFRUw3MK
    user:
      email: test@user.com
      logged_in: false
      name: Test User
      password: $2b$12$Q.5J0GgUz6f33oq.ddEvEOPjrStWbVnpdnMzePDzKu.8k9ZUwSbUC
preauthorized:
  emails:
  - melsby@gmail.com
