cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    user:
      email: test@user.com
      logged_in: false
      name: Test User
      password: $2b$12$Q.5J0GgUz6f33oq.ddEvEOPjrStWbVnpdnMzePDzKu.8k9ZUwSbUC
preauthorized:
  emails:
  - melsby@gmail.com
